kind = "web"
previewPath = "/"
title = "OWAAR CLOUD"
version = "1.0.0"
id = "artifacts/owaar-cloud"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 22586
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/owaar-cloud run dev"

[services.env]
PORT = "22586"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/owaar-cloud", "run", "build"]
publicDir = "artifacts/owaar-cloud/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
